name: Elixir CI

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    env:
      MIX_ENV: test
      ELIXIR_ENV: test
    strategy:
      matrix:
        otp: ['20.3', '21.1', '22.3.4', '23.2.7']
        elixir: ['1.7.3', '1.11.4']
        exclude:
          - otp: '20.3'
            elixir: '1.11.4'
          - otp: '22.3.4'
            elixir: '1.7.3'
          - otp: '23.2.7'
            elixir: '1.7.3'


    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test

    - name: Formatter
      run: mix format --check-formatted
